name: Build and Publish
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Spark 3.1
        run: |
          mvn -B -e install -P3.1 -DskipTests
      - name: Build with Spark 3.2
        run: |
          mvn -B -e install -P3.2 -DskipTests
      - name: Build with Spark 3.3
        run: |
          mvn -B -e install -P3.3 -DskipTests
      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Stage artifacts
        run: |
          mkdir shaded-jars
          for file in spark-3.*/target/spark-3.*.jar; do
            if [[ "$file" == *"lib"* || "$file" == *"original"* ]]; then
              continue
            fi
            cp "$file" shaded-jars/
          done
      - name: Upload Shaded JARs
        uses: actions/upload-artifact@v4
        with:
          name: shaded-spark-spanner-jars-${{ steps.vars.outputs.sha_short }}
          path: shaded-jars/
